---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Vector service up and running
    ansible.builtin.service:
      name: vector
      state: started